# Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [11]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("world")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [12]:
print(result)

b'hello world'


In [13]:
a = tf.constant(10)
b = tf.constant(20)

In [14]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess: 
    result = sess.run(a + b)

In [16]:
result

30

In [17]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4),10)

In [19]:
myzeros = tf.zeros((4,4))

In [20]:
myones = tf.ones((4,4))

In [21]:
myrandn = tf.random_normal((4,4), mean = 0, stddev = 1.0)

In [23]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [24]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

Interacrtive session: only useful for notebook settings, it allows you to constantly call it from multiple cells (instead of with tf session)

In [25]:
sess = tf.InteractiveSession()

In [27]:
for op in my_ops: 
    print(sess.run(op)) #you can use op.eval() instead 
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-0.03037638  0.58986211  0.62280172  0.88653445]
 [ 1.28840518  1.00418222 -0.05134926 -0.17393702]
 [ 0.5308103   0.19323799  0.52428675  0.59167445]
 [ 0.89451772 -0.98649371 -0.1354132   0.16379054]]


[[ 0.62407005  0.6585443   0.92032099  0.10831809]
 [ 0.58998585  0.90898252  0.01523697  0.9276011 ]
 [ 0.76295543  0.04117966  0.54950678  0.53467405]
 [ 0.86598647  0.0165906   0.64843011  0.2542274 ]]




In [28]:
a = tf.constant([[1,2],[3,4]]) # 2*2

In [29]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [30]:
b = tf.constant([[10],[100]]) #2*1

In [31]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [32]:
result = tf.matmul(a,b)

In [33]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [34]:
result.eval()

array([[210],
       [430]], dtype=int32)

# Tensorflow Graphs

Graphs are sets of connected nodes (Vertices), connection between vertices are referred to as edges.

In tensorflow each node is an operation with posssible inputs that can supply some output. With Twnsorflow we will construct a graph and execute it. Tensorflow uses a default graph!

In [38]:
n1 =tf.constant(1)

In [39]:
n2 = tf.constant(2)

In [40]:
n3 = n1+n2

In [41]:
with tf.Session() as sess:
    result = sess.run(n3)

In [42]:
print(result)

3


In [43]:
print(n3)

Tensor("add_4:0", shape=(), dtype=int32)


When we start tensorflow a default graph is created! We actually create an additional graph pretty easily. 

In [45]:
print(tf.get_default_graph())

In [46]:
g = tf.Graph()

In [47]:
print(g)

In [48]:
graph_one = tf.get_default_graph()
print(graph_one)

In [49]:
graph_two = tf.Graph()

In [50]:
print(graph_two)

setting the graph two as a default graph

In [52]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [53]:
print(graph_two is tf.get_default_graph())

False


# Variables and Placeholders in Tensorflow

There are two main types of tensor objects in a graph: 
    1- Variables
    2- Placeholders

During the optimization process tensorflow tunes the parameters of the model to try to get a better fit on the training data. 
   
Variables can hold the values of weight and biases. Varibales do need to be intialized.    
Placeholders are intianlly empty and are used to feed the actual trainig examples. 
However they do need a declared expected data type with and optional shape argument.

In [54]:
sess = tf.InteractiveSession()

In [55]:
my_tensor = tf.random_uniform((4,4),0,1)

In [56]:
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [57]:
my_var = tf.Variable(initial_value=my_tensor)

In [58]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [59]:
sess.run(my_var) # it gives us an error because We should initialized variables

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable)]]

In [60]:
init = tf.global_variables_initializer() # initialize the variables

In [62]:
sess.run(init)

In [63]:
sess.run(my_var)

array([[ 0.64422739,  0.66181993,  0.15897667,  0.06271684],
       [ 0.25718427,  0.4313097 ,  0.89153421,  0.96266496],
       [ 0.82328188,  0.53581417,  0.97797585,  0.32609248],
       [ 0.52748966,  0.4339354 ,  0.53203535,  0.82812107]], dtype=float32)

In [66]:
ph = tf. placeholder(tf.float32, shape=(None,5)) # declare data type and shape, 32 is more than enough for our experiments
# the first attribute Npne is replace by the number os samples 